package langs

import (
	"github.com/gvcgo/gvc/pkgs/vctrl"
	"github.com/spf13/cobra"
)

func SetPython(reg IRegister) {
	pyCmd := &cobra.Command{
		Use:     "python",
		Aliases: []string{"py"},
		Short:   "Python related CLIs.",
	}

	remoteCmd := &cobra.Command{
		Use:     "remote",
		Aliases: []string{"r"},
		Short:   "Shows available versions from remote website.",
		Run: func(cmd *cobra.Command, args []string) {
			nv := vctrl.NewPyVenv()
			nv.ListRemoteVersions()
		},
	}
	pyCmd.AddCommand(remoteCmd)

	useCmd := &cobra.Command{
		Use:     "use",
		Aliases: []string{"u"},
		Short:   "Dowloads and switches to the specified version.",
		Long:    "Example: py u <version>",
		Run: func(cmd *cobra.Command, args []string) {
			if len(args) == 0 {
				cmd.Help()
				return
			}
			nv := vctrl.NewPyVenv()
			nv.InstallVersion(args[0], false)
		},
	}
	pyCmd.AddCommand(useCmd)

	localCmd := &cobra.Command{
		Use:     "local",
		Aliases: []string{"l"},
		Short:   "Shows installed versions.",
		Run: func(cmd *cobra.Command, args []string) {
			nv := vctrl.NewPyVenv()
			nv.ShowInstalled()
		},
	}
	pyCmd.AddCommand(localCmd)

	removeCmd := &cobra.Command{
		Use:     "remove",
		Aliases: []string{"rm"},
		Short:   "Removes a specified version",
		Run: func(cmd *cobra.Command, args []string) {
			if len(args) == 0 {
				cmd.Help()
				return
			}
			nv := vctrl.NewPyVenv()
			nv.RemoveVersion(args[0])
		},
	}
	pyCmd.AddCommand(removeCmd)

	updatePyenvCmd := &cobra.Command{
		Use:     "update-pyenv",
		Aliases: []string{"up"},
		Short:   "Installs or updates pyenv/pyenv-win.",
		Run: func(cmd *cobra.Command, args []string) {
			nv := vctrl.NewPyVenv()
			nv.InstallPyenv()
		},
	}
	pyCmd.AddCommand(updatePyenvCmd)

	showPathCmd := &cobra.Command{
		Use:     "pyenv-path",
		Aliases: []string{"pp"},
		Short:   "Shows pyenv versions path.",
		Run: func(cmd *cobra.Command, args []string) {
			nv := vctrl.NewPyVenv()
			nv.ShowVersionPath()
		},
	}
	pyCmd.AddCommand(showPathCmd)

	winFixCmd := &cobra.Command{
		Use:     "fix-win",
		Aliases: []string{"fw"},
		Short:   "Remove python.exe generated by Windows system in ~/AppData/Local/Microsoft/WindowsApps .",
		Run: func(cmd *cobra.Command, args []string) {
			nv := vctrl.NewPyVenv()
			nv.FixSystemGenerationsForWin()
		},
	}
	pyCmd.AddCommand(winFixCmd)

	reg.Register(pyCmd)
}
